exam_c/urls.py
from django.urls import path

from . import views

app_name = 'c'
urlpatterns = [
    path('', views.login, name='login'),
    path('loginsecond/<exampage_id>', views.login_second, name='login-second'),
    path('exampage/<exampage_id>', views.exampage, name='exampage'),
    path('exampage/<exampage_id>/choicequestion/<int:choice_question_id>', views.exampage_choice_question, name='exampage-choicequestion'),
    path('exampage/<exampage_id>/codingquestion/<int:coding_question_id>', views.exampage_coding_question, name='exampage-codingquestion'),
    path('exampage/<exampage_id>/completequestion/<int:question_id>', views.exampage_complete_question, name='exampage-completequestion'),
    path('examroom/<int:exam_id>', views.exam_room, name='examroom'),
    path('api/sendchoiceanswer/<exampage_id>/<int:choice_question_id>/<int:choice_id>', views.api_handle_choice_answer,name='api-choiceanswer'),
    path('api/getchoicetext/<exampage_id>/<int:choice_question_id>', views.api_get_choice_text,name='api-choicetext'),
    path('api/getchoicestatus/<exampage_id>', views.api_get_choice_status,name='api-getchoicestatus'),
    path('api/setchoicefininshed/<exampage_id>', views.api_set_choice_finished,name='api-setchoicefinished'),
    
    path('api/getservertime/<exampage_id>', views.api_get_server_time,name='api-getservertime'),
    path('api/download/scorelist<int:exam_id>.txt', views.api_download_scorelist, name='api-download-scorelist'),
    path('api/download/codingzip/<exampage_id>/<int:coding_question_id>', views.api_download_coding_zipfile, name='api-download-coding-zipfile'),
    path('api/submitall/<exampage_id>', views.api_submit_all, name='api-submit-all'),
    path('api/addtime/<exampage_id>', views.add_time_enable, name='api-addtime'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('c/', include('exam_c.urls')),
    path('admin/', admin.site.urls),
]

exam_c/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from django.utils import timezone
import datetime

from .models import Student, Exam

class StudentForm(forms.Form):
    exam_id = forms.IntegerField(label='考试编号')
    name = forms.CharField(label='姓名',  max_length=50)
    student_id = forms.CharField(label='学号')

    def clean(self):
        cleaned_data = super().clean()
        exam_id = cleaned_data['exam_id']
        student_id = str(cleaned_data['student_id'])

        if not Exam.objects.filter(id=exam_id, opened=True).exists():
            self.add_error('exam_id', '考试编号不存在')
        if not Student.objects.filter(student_id=student_id).exists():
            self.add_error('student_id', '学号不存在')
        

class StudentFormSecondLogin(forms.Form):
    exam_id = forms.IntegerField(label='考场编号')
    name = forms.CharField(label='姓名',  max_length=50)
    student_id = forms.CharField(label='学号', max_length=50)
    password = forms.CharField(label='登录密码', max_length=50, widget=forms.PasswordInput(attrs={"class":"form-control"}))

    def clean(self):
        cleaned_data = super().clean()
        exam_id = cleaned_data['exam_id']
        student_id = str(cleaned_data['student_id'])
        try:
            password = str(cleaned_data['password'])
        except: 
            password = ''

        if not Exam.objects.filter(id=exam_id, opened=True).exists():
            self.add_error('exam_id', '考试编号不存在')
            return
        if not Student.objects.filter(student_id=student_id).exists():
            self.add_error('student_id', '学号不存在')
            return
        if Exam.objects.get(id=exam_id).passwd_second_login != password:
            self.add_error('password', '输入正确密码')


class UploadOutputFileForm(forms.Form):
    file = forms.FileField()


class CompleteForm(forms.Form):
    position1 = forms.CharField(label='代码①')
    position2 = forms.CharField(label='代码②')
    position3 = forms.CharField(label='代码③')

exam_c/views.py
from django.shortcuts import render
from django.http import HttpResponse

from django.http import HttpResponse, HttpResponseRedirect, FileResponse
from django.urls import reverse
from django import forms
from django.http import Http404

from django.views.decorators.csrf import csrf_exempt
import json
import datetime
import time
import random
from pathlib import Path

from .models import *
from .forms import StudentForm, UploadOutputFileForm, StudentFormSecondLogin, CompleteForm
# Create your views here.

BASE_DIR = Path(__file__).resolve().parent.parent
MEDIA_ROOT  = BASE_DIR / 'media'

# def index(request):
#     exam_list = Exam.objects.all()
#     return render(request, 'exam_c/index.html')


def exampage(request, exampage_id):
    try:
        exam_page = ExamPaper.objects.get(unique_key=exampage_id)
    except ExamPaper.DoesNotExist:
        return HttpResponseRedirect(reverse('c:login'))

    question_links = []
    for a in exam_page.choice_question_answers_():
        if a=='+': question_links.append('btn btn-light')
        else: question_links.append('btn btn-success')
    context = {
        'exam': exam_page.exam,
        'student': exam_page.student,
        'question_links': question_links,
        'exam_page': exam_page,
        'choice_questions_answers': exam_page.choice_question_answers_(),
        'coding_questions_answers': exam_page.coding_question_answers_(),
        }
    return render(request, 'exam_c/exam_page.html', context)

def exampage_choice_question(request, exampage_id, choice_question_id):
    try:
        exam_page = ExamPaper.objects.get(unique_key=exampage_id)
    except ExamPaper.DoesNotExist:
        return HttpResponseRedirect(reverse('c:login'))

    choice_question_id = 1  # fix the id 
    question_links = []
    # for a in exam_page.choice_question_answers_():
    #     if a=='+': question_links.append('btn btn-light')
    #     else: question_links.append('btn btn-success')
    # question_links[choice_question_id-1] = 'btn btn-primary'
    current_choice = exam_page.choice_question_answers_()[choice_question_id-1]
    if current_choice=='+': current_choice=''
    context = {
        'exam': exam_page.exam,
        'student': exam_page.student,
        'exam_page': exam_page,
        'question_links': question_links,
        'current_choice': current_choice,
        'choice_question': exam_page.choice_questions_pk_(choice_question_id),
        'choice_question_id': choice_question_id,
        }
    return render(request, 'exam_c/exam_page_choice_question.html', context)


def exampage_complete_question(request, exampage_id, question_id):
    try:
        exam_page = ExamPaper.objects.get(unique_key=exampage_id)
    except ExamPaper.DoesNotExist:
        return HttpResponseRedirect(reverse('c:login'))
    
    uploadsucc = False
    question = exam_page.complete_questions_pk_(question_id)
    if request.method == 'POST':
        form = CompleteForm(request.POST)
        if form.is_valid():
            cleaned_data = form.cleaned_data
            answers = [cleaned_data['position1'], cleaned_data['position2'],cleaned_data['position3'] ]
            print("answers: ", answers)
            exam_page.update_complete_question_answer_result_(question_id, answers)
            uploadsucc = True
    else:
        answers = exam_page.complete_question_answers_()[question_id-1].split(',')
        if len(answers) == 3:
            data = {'position1': answers[0], 
                    'position2': answers[1], 
                    'position3': answers[2],
                    }
            form = CompleteForm(data)
        else:
            form = CompleteForm()

    if (not exam_page.enabled) or (not exam_page.choice_question_finished):
        form.fields['position1'].widget.attrs['disabled'] = True
        form.fields['position2'].widget.attrs['disabled'] = True
        form.fields['position3'].widget.attrs['disabled'] = True

    context = {
        'exam_page': exam_page,
        'question': question,
        'question_id': question_id,
        'uploadsucc': uploadsucc,
        'form': form,
        }
    return render(request, 'exam_c/exam_page_complete_question.html', context)


def handle_uploaded_file(f, output_save_path):
    # print(os.path.join(root_path,filename))
    with open(output_save_path, 'wb') as destination:
        for chunk in f.chunks():
            destination.write(chunk)

def exampage_coding_question(request, exampage_id, coding_question_id):
    try:
        exam_page = ExamPaper.objects.get(unique_key=exampage_id)
    except ExamPaper.DoesNotExist:
        return HttpResponseRedirect(reverse('c:login'))
    
    uploadsucc = False
    coding_question = exam_page.coding_questions_pk_(coding_question_id)
    if request.method == 'POST':
        form = UploadOutputFileForm(request.POST, request.FILES)
        if form.is_valid():
            output_save_path = exam_page.coding_output_path_(coding_question_id)
            handle_uploaded_file(request.FILES['file'], output_save_path)
            ## update coding answers
            # old_answers = exam_page.coding_question_answers.split(',')
            # old_answers[coding_question_id-1] = str(output_save_path)
            # exam_page.coding_question_answers = ','.join(old_answers)
            # exam_page.save()
            exam_page.update_coding_question_answer_result_(coding_question_id, output_save_path)
            uploadsucc = True
    else:
        form = UploadOutputFileForm()
    if (not exam_page.enabled) or (not exam_page.choice_question_finished):
        form.fields['file'].widget.attrs['disabled'] = True

    context = {
        'exam': exam_page.exam,
        'student': exam_page.student,
        'exam_page': exam_page,
        'coding_questions_answers': exam_page.coding_question_answers_(),
        'coding_question': exam_page.coding_questions_pk_(coding_question_id),
        'coding_question_id': coding_question_id,
        'uploadsucc': uploadsucc,
        'form': form,
        }
    return render(request, 'exam_c/exam_page_coding_question.html', context)



import socket
def get_host_ip():
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.connect(('8.8.8.8', 80))
        ip = s.getsockname()[0]
    finally:
        s.close()
    return ip


def exam_room(request, exam_id):
    try:
        exam = Exam.objects.get(id=exam_id)
    except Exam.DoesNotExist:
        raise Http404("exam does not exist")
    
    exam_papers = exam.exampaper_set.order_by('student_id')
    # for exam_paper in exam_papers:
        # print(exam_paper.student, exam_paper.student.id)
    context = {
        'exam': exam,
        'exam_id': exam_id,
        'exam_papers': exam_papers,
        'login_url': 'http://'+get_host_ip()+':8000/c',
        }
    return render(request, 'exam_c/exam_room_detail.html', context)



def login(request):

    if request.method == 'POST':
        # 如果登录成功，绑定参数到cookie中，set_cookie
        form = StudentForm(request.POST)

        if form.is_valid():
            cleaned_data = form.cleaned_data
            # print(cleaned_data)

            # 查询用户是否在数据库中
            exam_id = cleaned_data['exam_id']
            student_id = cleaned_data['student_id']
            unique_key = str(exam_id)+'-'+str(student_id)

            exam = Exam.objects.get(pk=exam_id)
            student = Student.objects.get(student_id=student_id)

            # 检查该考场和学号对应的试卷是否存在，不存在就创建新的试卷
            # 同时随机抽取题目
            choice_question_numb, coding_question_numb = exam.choice_question_num, exam.coding_question_num
            exam_paper, created = ExamPaper.objects.get_or_create(student=student, exam=exam, unique_key=unique_key)
            if created or exam_paper.is_empty_():
                exam_paper.problem_type = exam.problem_type
                exam_paper.start_time = datetime.datetime.now()

                exam_paper.student_id_local = student_id
                exam_paper.exam_id_local = exam_id

                #########
                choice_questions_ids = [str(x['id']) for x in ChoiceQuestion.objects.values('id')]
                choice_questions_ids = random.sample(choice_questions_ids, choice_question_numb)
                exam_paper.choice_questions = ','.join(choice_questions_ids)
                exam_paper.choice_question_answers = ','.join(['+' for i in range(len(choice_questions_ids))])
                exam_paper.choice_question_results = ','.join(['0' for i in range(len(choice_questions_ids))])

                #########
                complete_questions_ids = [str(x['id']) for x in CompleteQuestion.objects.values('id')]
                complete_questions_ids = random.sample(complete_questions_ids, exam.complete_question_num)
                exam_paper.complete_questions = ','.join(complete_questions_ids)
                exam_paper.complete_question_answers = '\n'.join(['#' for i in range(len(complete_questions_ids))])
                exam_paper.complete_question_results = ','.join(['0' for i in range(len(complete_questions_ids))])

                #########
                code_questions_ids = [str(x['id']) for x in CodingQuestion.objects.values('id')]
                code_questions_ids = random.sample(code_questions_ids, coding_question_numb)
                exam_paper.coding_questions = ','.join(code_questions_ids)
                exam_paper.coding_question_answers = ','.join(['+' for i in range(len(code_questions_ids))])
                exam_paper.coding_question_results = ','.join(['0' for i in range(len(code_questions_ids))])
                exam_paper.save()

            diff = int(timezone.now().timestamp() - exam_paper.start_time.timestamp())
            if diff<60: 
                return HttpResponseRedirect(reverse('c:exampage', args=(exam_paper.unique_key,)))
            else:
                return HttpResponseRedirect(reverse('c:login-second', args=(exam_paper.unique_key,)))
    else:
        form = StudentForm()

    context = {

exam_c/templates/exam_c/exam_page.html
{% load static %}

<!DOCTYPE html>
<html lang="zh-CN">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
  <meta name="description" content="">
  <meta name="author" content="">

  <title>C语言考试页面</title>

  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" type="text/css" href="{% static 'exam_c/css/bootstrap.min.css' %}">

  <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
  <!-- <link href="../../assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet"> -->

  <!-- Custom styles for this template -->
  <!-- <link href="starter-template.css" rel="stylesheet"> -->

  <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
  <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
  <!-- <script src="../../assets/js/ie-emulation-modes-warning.js"></script> -->

  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
      <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

  <style>
    body {
      padding-top: 50px;
    }

    .starter-template {
      padding: 40px 15px;
      text-align: center;
    }

    .btn-start {
      background-color: white;
      color: green;
      padding: 2px 2px;
      margin-top: 2px;
    }

    .btn-start:disabled {
      background-color: gray;
      color: gainsboro;
      padding: 2px 2px;
      margin-top: 2px;
    }
  </style>
</head>

<body>

  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
          aria-expanded="false" aria-controls="navbar">
        </button>
        <a class="navbar-brand" href="#">C语言期末考试</a>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><a href="{% url 'c:exampage'  exam_page.unique_key %}">首页</a></li>
        </ul>
      </div>
      <!--/.nav-collapse -->
    </div>
  </nav>

  <div class="container">

    <div class="card" style="width: 90%;">
      <div class="card-body">
        {% if not exam_page.enabled %}
        <h3>{{ exam.exam_type_ }}期末考试(交卷成功，不能再作答)</h3>
        {% else %}
        <h3>{{ exam.exam_type_ }}期末考试</h3>
        {% endif %}
        <p>考场编号： {{ exam.id }}</p>
        <p>考生信息： {{ student.class_name }}--{{ student.student_name }}--{{ student.student_id }}</p>
        {% if exam_page.add_time %}
        <p>考试时长： {{ exam.period_ }}+延时{{ exam_page.add_time }}分钟 </p>
        {% else %}
        <p>考试时长： {{ exam.period_ }} </p>
        {% endif %}

        <strong>剩余时间： <span id="usedTime"></span></strong>
      </div>
    </div>

    <HR style=" FILTER: alpha (opacity = 100, finishopacity =0 , style= 2 )" width="100%" color=#987 cb 9 SIZE=20>

    <div class="card" style="width: 90%;">
      <div class="card-body">
        <h2 class="card-title">选择题
          <button id="start-choice" class="btn-start" style="margin:16px 20px">>>></button>
        </h2>
        <div class="btn-group" role="group" aria-label="choice questions">
          {% for a in question_links %}
          <span class="{{ a }}">
            题{{ forloop.counter }}</span>
          {% endfor %}
        </div>
      </div>
    </div>

    <HR style=" FILTER: alpha (opacity = 100, finishopacity =0 , style= 2 )" width="100%" color=#987 cb 9 SIZE=20>

    <div class="card" style="width: 60%;">
      <div class="card-body">
        <h2 class="card-title">填空题
          {% if exam_page.choice_question_finished %}
          <button id="start-complete" class="btn-start" style="margin:16px 20px">>>></button>
          {% else %}
          <button id="start-complete" class="btn-start" style="margin:16px 20px" disabled>>>></button>
          {% endif %}
        </h2>
        <div class="btn-group" role="group" aria-label="coding questions">
          {% for a in exam_page.complete_question_answers_ %}
          {% if a == '#' %}
          <span class="btn btn-light">
            题{{ forloop.counter }}</span></li>
          {% else %}
          <span class="btn btn-success">
            题{{ forloop.counter }}</span></li>
          {% endif %}
          {% endfor %}
        </div>
      </div>
    </div>

    <HR style=" FILTER: alpha (opacity = 100, finishopacity =0 , style= 2 )" width="100%" color=#987 cb 9 SIZE=20>

    <div class="card" style="width: 60%;">
      <div class="card-body">
        <h2 class="card-title">编程题
          {% if exam_page.choice_question_finished %}
          <button id="start-coding" class="btn-start" style="margin:16px 20px">>>></button>
          {% else %}
          <button id="start-coding" class="btn-start" style="margin:16px 20px" disabled>>>></button>
          {% endif %}
        </h2>
        <div class="btn-group" role="group" aria-label="coding questions">
          {% for a in coding_questions_answers %}
          {% if a == '+' %}
          <span class="btn btn-light">
            题{{ forloop.counter }}</span></li>
          {% else %}
          <span class="btn btn-success">
            题{{ forloop.counter }}</span></li>
          {% endif %}
          {% endfor %}
        </div>
      </div>
    </div>

    <HR style=" FILTER: alpha (opacity = 100, finishopacity =0 , style= 2 )" width="100%" color=#987 cb 9 SIZE=20>

    <div style="width: 60%; border: 2px solid; border-color: goldenrod; text-align: center;">
      {% if exam_page.enabled %}
      <button id="submit-all" class="btn-upload" style="margin:5px auto;font-size: large;">交卷</button>
      {% else %}
      <button id="submit-all" class="btn-upload" style="margin:5px auto;font-size: large;" disabled>交卷</button>
      {% endif %}
    </div>

  </div><!-- /.container -->



  <!-- Bootstrap core JavaScript
    ================================================== -->
  <!-- Placed at the end of the document so the pages load faster -->
  <script src="{% static 'exam_c/js/jquery-3.6.0.min.js' %}"></script>
  <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
  <script src="{% static 'exam_c/js/bootstrap.min.js' %}"></script>
  <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
  <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>

  <script type="text/javascript">
    $('#start-coding').on('click', function () {
      window.location.href = "{% url 'c:exampage-codingquestion'  exam_page.unique_key  1 %}";
    });

    $('#start-choice').on('click', function () {
      window.location.href = "{% url 'c:exampage-choicequestion'  exam_page.unique_key  1 %}";
    });

    $('#start-complete').on('click', function () {
      window.location.href = "{% url 'c:exampage-completequestion'  exam_page.unique_key  1 %}";
    });

  </script>

  <script type="text/javascript">
    function submitall_fresh() {
      $.ajax({
        url: '/c/api/submitall/{{ exam_page.unique_key }}',
        type: 'POST',
        data: {},
        dataType: 'json',
        timeout: 10000,
        success: function (result) {
          location.reload();
          $('#show').html();
        }
      });
    }
  </script>

  <script type="text/javascript">
    $('#submit-all').on('click', function () {
      var Val = confirm("确认结束作答并交卷?");
      if (Val == true) {
        submitall_fresh();
      }
    });
  </script>

  <script type="text/javascript">
    function refreshTime() {
      $.ajax({
        url: '/c/api/getservertime/{{ exam_page.unique_key }}',
        type: 'POST',
        data: {},
        dataType: 'json',
        timeout: 10000,
        success: function (result) {
          if (result.result) {
            $("#usedTime").html(result.result);
            if (result.color) {
              $("#usedTime").css({ 'color': result.color });
            }
            if (result.refresh) {
              location.reload();
            }
          }
        }
      });
      setTimeout('refreshTime()', 5000);
    }
    setTimeout('refreshTime()', 10);
  </script>
</body>

</html>

exam_c/templates/exam_c/exam_room_detail.html
{% load static %}


<!DOCTYPE html>
<html lang="zh-CN">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
  <meta name="description" content="">
  <meta name="author" content="">
  <meta http-equiv="refresh" content="60">

  <title>C语言考试管理页面</title>

  <!-- Bootstrap core CSS -->
  <!-- <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet"> -->
  <link rel="stylesheet" type="text/css" href="{% static 'exam_c/css/bootstrap.min.css' %}">
  <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
  <!-- <link href="../../assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet"> -->


  <style>
    body {
      padding-top: 50px;
    }

    .starter-template {
      padding: 40px 15px;
      text-align: center;
    }

    .box {
      -webkit-user-select: none;
      -moz-user-select: none;
      -ms-user-select: none;
      user-select: none;
    }

    .btn-upload {
      background-color: lightgreen;
      border: 0ch;
      color: white;
      padding: 2px 2px;
      margin-top: 2px;
    }

    .btn-download {
      display: inline-block;
      background-color: lightgray;
      border: 0ch;
      color: black;
      padding: 6px 6px;
      margin: 10px 20px;
      font-size: 15px;
    }
  </style>
</head>

<body>

  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
          aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#"></a>
      </div>
      <!-- <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="#">{{ exam.exam_type_ }}</a></li>
                    <li><a href="#">{{ exam.period_ }}</a></li>
                </ul>
            </div> -->
      <!--/.nav-collapse -->
    </div>
  </nav>


  <div class="jumbotron">
    <div class="container">
      <h1>{{ exam.exam_type_ }}<small>在线考试系统</small></h1>
      <p>考试登陆网址: {{ login_url }} </p>
      <p>考场编号: {{ exam.id }} </p>
      <p><strong>|请将考试网址和考场编号告知考生|</strong></p>
      <p>考试时长: {{ exam.period_ }}</p>
      <p>考试人数: {{ exam_papers.count }}</p>
    </div>
  </div>

  <div class="container">

    <div class="starter-template">
      <h1>考生列表 <a type="button" class="btn btn-info" href="{% url 'c:api-download-scorelist' exam_id %}">导出成绩</a></h1>

      <table class="table table-striped table-bordered">
        <tr>
          <th>#</th>
          <td>班级</td>
          <td>姓名</td>
          <td>学号</td>
          <td>开考时间</td>
          <td>选择题</td>
          <td>填空题</td>
          <td>编程题</td>
          <td>总分</td>
          <td>是否交卷</td>
        </tr>
        {% for exam_paper in exam_papers %}
        <tr>
          <th scope="row">{{ forloop.counter }}</th>
          <td>{{ exam_paper.student.class_name }}</td>
          <td>{{ exam_paper.student.student_name }}</td>
          <td>{{ exam_paper.student.student_id }}</td>
          <td>{{ exam_paper.start_time_ }}</td>
          <td>{{ exam_paper.choice_question_result_detail }}</td>
          <td>{{ exam_paper.complete_question_result_detail }}</td>
          <td>{{ exam_paper.coding_question_result_detail }}</td>
          <td>{{ exam_paper.total_score }}</td>
          <td>{{ exam_paper.is_ended_ }}</td>
        </tr>
        {% endfor %}
      </table>

    </div>

  </div><!-- /.container -->


  <!-- Bootstrap core JavaScript
    ================================================== -->
  <!-- Placed at the end of the document so the pages load faster -->
  <script src="{% static 'exam_c/js/jquery-3.6.0.min.js' %}"></script>
  <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
  <script src="{% static 'exam_c/js/bootstrap.min.js' %}"></script>
  <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
  <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
</body>

</html>

exam_c/templates/exam_c/form_item.html
    <div class="fieldWrapper">
        
        <label for="{{ form_item.id_for_label }}">{{ form_item.label }}</label>
        {{ form_item }}  {{ form_item.errors }}
    </div>